### ISSUE TITLE
Cannot reproduce MELD result

### ISSUE THREAD

**Issue by sailist** [hujingwen6666/MMGCN#4]
I can only got f1-score of 0.5760, here is the confusion matrix from stdout output log
```
              precision    recall  f1-score   support

           0     0.7017    0.8503    0.7689      1256
           1     0.4492    0.4875    0.4676       281
           2     0.0000    0.0000    0.0000        50
           3     0.4138    0.1154    0.1805       208
           4     0.5358    0.5398    0.5378       402
           5     0.0000    0.0000    0.0000        68
           6     0.4594    0.4261    0.4421       345

    accuracy                         0.6103      2610
   macro avg     0.3657    0.3456    0.3424      2610
weighted avg     0.5623    0.6103    0.5760      2610

[[1068   57    0   19   78    0   34]
 [  74  137    0    0   35    0   35]
 [  28    5    0    0    8    0    9]
 [ 121   16    0   24   13    0   34]
 [ 109   31    0    4  217    0   41]
 [  33   10    0    2    3    0   20]
 [  89   49    0    9   51    0  147]]
```

The command is:
```
python train.py --base-model LSTM --graph-model --nodal-attention --dropout 0.4 --lr 0.001 --batch-size 16 --l2 0.0 --graph_type=MMGCN --epochs=60 --graph_construct=direct --multi_modal --mm_fusion_mthd=concat_subsequently --modals=avl --Dataset=MELD --Deep_GCN_nlayers 4 --use_speaker
```

**Comment by Coding511** [comment]
@sailist Hi did you try on colab or your machine?

**Comment by sailist** [comment]
> @sailist Hi did you try on colab or your machine?

This is my implemented result, just ran on my machine.

**Comment by Coding511** [comment]
@sailist Thanks for the reply.
Here the Iemocap features are different then in Cogmen, Have you noticed?
Only structure is same but feature size is different.

**Comment by sailist** [comment]
@Coding511 You can get the answer from [this](https://github.com/Exploration-Lab/COGMEN/issues/1#issuecomment-1175634604) and [this](https://github.com/Exploration-Lab/COGMEN/issues/1#issuecomment-1195103888).

**Comment by Coding511** [comment]
went through both these pages already. The pickle file sizes are different here from COGMEN.
could you please tell me the steps to execute this MMGCN code.

I tried training from scratch, but its not working.

**Comment by sailist** [comment]
Just choose one feature file and ignore the other one, there is no need to merge them. For your training problem, try debug, I can directly run this code (maybe with small change), you can solve this question by your own. If you still can't, try pasting the full screenshot of your bug here.

**Comment by Coding511** [comment]
This is the output I am getting after executing train.py in spyder IDE.

```
Namespace(no_cuda=False, base_model='LSTM', graph_model=False, nodal_attention=False, windowp=10, windowf=10, lr=0.0001, l2=1e-05, rec_dropout=0.1, dropout=0.5, batch_size=32, epochs=60, class_weight=False, active_listener=False, attention='general', tensorboard=False, graph_type='relation', use_topic=False, alpha=0.2, multiheads=6, graph_construct='full', use_gcn=False, use_residue=True, multi_modal=False, mm_fusion_mthd='concat', modals='avl', av_using_lstm=False, Deep_GCN_nlayers=256, Dataset='IEMOCAP', use_speaker=False, use_modal=False)
Running on CPU
Traceback (most recent call last):

  File "/home/codingpython/global/MULTIMODAL/MMGCN-master/train.py", line 360, in <module>
    raise NotImplementedError

NotImplementedError
```

**Comment by sailist** [comment]
see `./run.sh`, you need to add multi_modal arg in you command

**Comment by Coding511** [comment]
Thank you so much.
No matter what base_model I am taking, it is giving dimension error. Did you get any of them? Which model is performing best here?
In LSTM, I am getting this traceback.

```
Namespace(no_cuda=False, base_model='LSTM', graph_model=False, nodal_attention=False, windowp=10, windowf=10, lr=0.0001, l2=1e-05, rec_dropout=0.1, dropout=0.5, batch_size=32, epochs=60, class_weight=False, active_listener=False, attention='general', tensorboard=False, graph_type='relation', use_topic=False, alpha=0.2, multiheads=6, graph_construct='full', use_gcn=False, use_residue=True, multi_modal=True, mm_fusion_mthd='concat', modals='avl', av_using_lstm=False, Deep_GCN_nlayers=256, Dataset='IEMOCAP', use_speaker=False, use_modal=False)
Running on CPU
Basic LSTM Model.
Traceback (most recent call last):

  File "/home/codingpython/global/MULTIMODAL/MMGCN-master/train.py", line 496, in <module>
    train_loss, train_acc, _, _, _, train_fscore, _ = train_or_eval_model(model, loss_function, train_loader, e, optimizer, True)

  File "/home/codingpython/global/MULTIMODAL/MMGCN-master/train.py", line 117, in train_or_eval_model
    log_prob, alpha, alpha_f, alpha_b, _ = model(textf, qmask, umask)

  File "..../python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/codingpython/global/MULTIMODAL/MMGCN-master/model.py", line 433, in forward
    emotions, hidden = self.lstm(U)

  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 759, in forward
    self.check_forward_args(input, hx, batch_sizes)

  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 684, in check_forward_args
    self.check_input(input, batch_sizes)

  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 205, in check_input
    raise RuntimeError(

RuntimeError: input.size(-1) must be equal to input_size. Expected 2024, got 100
```

**Comment by sailist** [comment]
Emmmm..., you need to recheck your modification, after delete unused library and .cuda() operation and install torch_geometry, I can directly run commands in `./run.sh` without any exceptions for BOTH meld and iemocap dataset.

**Comment by Coding511** [comment]
> Emmmm..., you need to recheck your modification, after delete unused library and .cuda() operation and install torch_geometry, I can directly run commands in `./run.sh` without any exceptions for BOTH meld and iemocap dataset.

recheck modifications meaning?
I did not change anything except multimodal,
I am using editor to run this, not command line.
I don't know how to that?

**Comment by sailist** [comment]
So, try run the followed command in your Editor or shell under this repository, if you don't know how to run, google 'run shell command' 'change working directory' 'command argument' and learn these concepts. 
```
python train.py --base-model 'LSTM' --graph-model --nodal-attention --dropout 0.4 --lr 0.0003 --batch-size 16 --l2 0.00003 --graph_type='MMGCN' --epochs=20 --graph_construct='direct' --multi_modal --mm_fusion_mthd='concat_subsequently' --modals='avl' --Dataset='IEMOCAP' --Deep_GCN_nlayers 4 --class-weight --use_speaker
```

**Comment by Coding511** [comment]
@sailist I don't know how your code is working in the command prompt.
But from scratch or line by line, this code is giving shape errors in the editor.

like the shape of `textf` is `torch.Size([94, 32, 100])`, 
How can you apply this shape as input to `nn.LSTM()`?

What I want to state is the feature pickle fine or dataloader is giving the wrong shape., does not matter what modality you are selecting the last dimension is 100 only.

can anyone please clear this?

**Comment by Coding511** [comment]
@sailist @hujingwen6666 
Getting the errors below if anyone can solve them please:


Namespace(Dataset='IEMOCAP', Deep_GCN_nlayers=256, active_listener=False, alpha=0.2, attention='general', av_using_lstm=False, base_model='LSTM', batch_size=32, class_weight=False, dropout=0.5, epochs=60, graph_construct='full', graph_model=True, graph_type='relation', l2=1e-05, lr=0.0001, mm_fusion_mthd='concat', modals='al', multi_modal=True, multiheads=6, no_cuda=False, nodal_attention=False, rec_dropout=0.1, tensorboard=False, use_gcn=False, use_modal=False, use_residue=True, use_speaker=False, use_topic=False, windowf=10, windowp=10)
Running on CPU
construct relation graph
Graph NN with LSTM as base model.

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[/content/gdrive/MyDrive/MMGCN-master/train.py](https://localhost:8080/#) in <module>
    489 
    490         if args.graph_model:
--> 491             train_loss, train_acc, _, _, train_fscore, _, _, _, _, _ = train_or_eval_graph_model(model, loss_function, train_loader, e, cuda, args.modals, optimizer, True, dataset=args.Dataset)
    492             valid_loss, valid_acc, _, _, valid_fscore, _, _, _, _, _ = train_or_eval_graph_model(model, loss_function, valid_loader, e, cuda, args.modals, dataset=args.Dataset)
    493             test_loss, test_acc, test_label, test_pred, test_fscore, _, _, _, _, _ = train_or_eval_graph_model(model, loss_function, test_loader, e, cuda, args.modals, dataset=args.Dataset)

5 frames

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

TypeError: forward() takes from 3 to 4 positional arguments but 5 were given
